### ISSUE TITLE
Request for latest source code

### ISSUE THREAD

**Issue by hafijulali** [GittyMac/WalletCount#12]
I got the app from f-droid store but the source code on this repo doesn't match with the app downloaded from f-droid. I know GH issues is not the right way. but I didn't had any other way to reach out to you.

**Comment by GittyMac** [comment]
F-Droid compiles apps from the latest release tag, which in WalletCount's case is v2.0. [Here's a link to the source tree of v2.0.](https://github.com/GittyMac/WalletCount/tree/v2.0) You could also download the source code from the releases page.

**Comment by hafijulali** [comment]
Thanks got it. 

I am trying to customise the app for my own needs. So basically i have just a few categories of expenditure that i do frequently like food, entertainment or travel. So i wanted to make preset buttons for these and a persistent numeric pad on screen to enter the amount. So that I don't need to manually type these everytime I'm adding the expense amount.

Btw thanks for quick response :) Have a great day ahead
